version: '3.3'

x-shared: &shared
    image: n8nio/n8n
    environment:
      - WEBHOOK_URL=http://n8n.ddpp.local/
      - GENERIC_TIMEZONE=Europe/Paris
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=2048
      - EXECUTIONS_MODE=queue
      - EXECUTIONS_QUEUE=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - QUEUE_BULL_REDIS_HOST=n8n_redis
      - QUEUE_BULL_REDIS_PORT=6379
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_pgdb
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_db
      - DB_POSTGRESDB_PASSWORD=n8n_pwd
    depends_on:
      - n8n_redis
      - n8n_pgdb
    links:
      - n8n_pgdb
      - n8n_redis
    volumes:
      - ./.n8n:/home/node/.n8n
    networks:
      - ddpp
      - n8n_network
    restart: unless-stopped

services:
  n8n_app:
    <<: *shared
    environment:
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
    ports:
      - 5678

  n8n_app_worker:
    <<: *shared
    command: worker
    depends_on:
      - n8n_app

  n8n_redis:
    image: redis:6-alpine
    volumes:
      - ./redis-data:/data
    networks:
      - ddpp
      - n8n_network
    restart: always

  n8n_pgdb:
    image: postgres:15
    environment:
      - POSTGRES_SHARED_BUFFERS=2GB
      - POSTGRES_MAINTENANCE_WORK_MEM=1GB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=2GB
      - POSTGRES_WORK_MEM=64MB
      - POSTGRES_MAX_PARALLEL_WORKERS=10
      - POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER=5
      - POSTGRES_DB=n8n_db
      - POSTGRES_USER=n8n_db
      - POSTGRES_PASSWORD=n8n_pwd
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - n8n_network

networks:
  ddpp:
    external: true
  n8n_network:
    driver: bridge
