###############################################################
#                   Authelia configuration                    #
###############################################################

server:
  host: 0.0.0.0
  port: 9091

jwt_secret: a-super-long-strong-string-of-letters-numbers-characters
log:
  level: debug

default_redirection_url: https://data.ddpp.ovh
totp:
  issuer: ddpp.ovh
  period: 30
  skew: 1

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64

access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain:
        - "auth.data.ddpp.ovh"
      policy: bypass
    - domain:
        - "airbyte.data.ddpp.ovh"
        - "prefect.data.ddpp.ovh"
      policy: one_factor

session:
  name: authelia_session
  secret: a-really-L0ng_s7r0ng-secr3t-st1nggggg-shoul0-be-used
  expiration: 3600
  inactivity: 7200
  domain: ddpp.ovh # Should match whatever your root protected domain is

  redis:
    host: authelia_redis_1
    port: 6379

regulation:
  max_retries: 5
  find_time: 2m
  ban_time: 10m

theme: dark

storage:
  encryption_key: a-very-long-strong-key-should-be-used-here
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
#  smtp:
#    username: dataops@ddpp.ovh
#    password: P@ssword!
#    host: smtp-relay.gmail.com
#    port: 25
#    sender: dataops@ddpp.ovh
#    subject: "[Authelia] {title}"
#    disable_require_tls: false
#    disable_html_emails: false
#    tls:
#      server_name: smtp-relay.gmail.com
#      skip_verify: false
#      minimum_version: TLS1.2
