version: '3.3'

services:
  matomo_db:
    image: mysql:8.1.0
    command: --max-allowed-packet=64MB
    environment:
      - MYSQL_ROOT_PASSWORD=m@tomo_pwd
    env_file:
      - ./db.env
    ports:
      - '3308:3306'
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always

  matomo:
    image: matomo:4.15.1
    environment:
      - MATOMO_USERNAME=matomo_user
      - MATOMO_PASSWORD=m@tomo_pwd
      - MATOMO_EMAIL=dataops@ppdd.org
      - MATOMO_HOST=matomo_db
    ports:
      - '8087:80'
      - '4446:443'
    volumes:
      - ./config:/var/www/html/config:rw
    depends_on:
      - db
    restart: always

volumes:
  matomo:

networks:
  default:
    external: true
    name: ddpp