version: '3.3'

services:
  matomo_db:
    image: mysql:8.1.0
    command: >
          bash -c "
          chmod 644 /etc/mysql/conf.d/*.cnf
          && /usr/local/bin/docker-entrypoint.sh mysqld
          "
    environment:
      - MYSQL_ROOT_PASSWORD=m@tomo_pwd
    env_file:
      - ./db.env
    ports:
      - '3308:3306'
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-data:/var/lib/mysql
    restart: always

  matomo_app:
    image: matomo:4.15.1
    env_file:
      - ./db.env
    ports:
      - '8087:80'
      - '4446:443'
    volumes:
      - ./config:/var/www/html/config:rw
    depends_on:
      - matomo_db
    restart: always

volumes:
  matomo_app:

networks:
  default:
    external: true
    name: ddpp